#!C:\Users\junes\OneDrive\Documents\Visual Studio 2015\Projects\pythonProject\aTravelOrganizer\aTravelOrganizer\env\Scripts\python.exe

import warnings
warnings.simplefilter('default', DeprecationWarning)

from logilab.common.pytest import run
run()
